package engine.pricing;

import java.math.BigDecimal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Adjustment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("AdjustmentName")
   private String adjustmentName;
   @org.kie.api.definition.type.Label("AdjustmentValue")
   private Double adjustmentValue;

   public Adjustment()
   {
   }

   public Adjustment(java.lang.String adjustmentName)
   {
      this.adjustmentName = adjustmentName;
   }

   public Adjustment(java.lang.Double adjustmentValue)
   {
      this.adjustmentValue = adjustmentValue;
   }

   public java.lang.String getAdjustmentName()
   {
      return this.adjustmentName;
   }

   public void setAdjustmentName(java.lang.String adjustmentName)
   {
      this.adjustmentName = adjustmentName;
   }

   public java.lang.Double getAdjustmentValue()
   {
      return this.adjustmentValue;
   }

   public void setAdjustmentValue(java.lang.Double adjustmentValue)
   {
      this.adjustmentValue = adjustmentValue;
   }

   public Adjustment(java.lang.String adjustmentName,
         java.lang.Double adjustmentValue)
   {
      this.adjustmentName = adjustmentName;
      this.adjustmentValue = adjustmentValue;
   }

}