package engine.pricing;

import java.math.BigDecimal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Input implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Product")
   private java.lang.String product;

   @org.kie.api.definition.type.Label("State")
   private java.lang.String state;

   @org.kie.api.definition.type.Label("ZIP")
   private int zip;

   @org.kie.api.definition.type.Label("CustomerScore")
   private int customerScore;

   @org.kie.api.definition.type.Label("VantageScore")
   private int vantageScore;

   @org.kie.api.definition.type.Label("Tier")
   private int tier;

   @org.kie.api.definition.type.Label("VehicleType")
   private java.lang.String vehicleType;

   @org.kie.api.definition.type.Label("VehicleModelYear")
   private int vehicleModelYear;

   @org.kie.api.definition.type.Label("VechicleMake")
   private java.lang.String vechicleMake;

   @org.kie.api.definition.type.Label("VehicleModel")
   private java.lang.String vehicleModel;

   @org.kie.api.definition.type.Label("VehicleMileage")
   private int vehicleMileage;

   @org.kie.api.definition.type.Label("VehicleClass")
   private java.lang.String vehicleClass;

   @org.kie.api.definition.type.Label("LTV")
   private BigDecimal ltv;

   @org.kie.api.definition.type.Label("PTI")
   private BigDecimal pti;

   @org.kie.api.definition.type.Label("DTI")
   private BigDecimal dti;

   @org.kie.api.definition.type.Label("LoanAmount")
   private int loanAmount;

   @org.kie.api.definition.type.Label("NetDownPayment")
   private int netDownPayment;

   @org.kie.api.definition.type.Label("LoanTerm")
   private int loanTerm;

   @org.kie.api.definition.type.Label("VehicleValue")
   private int vehicleValue;

   @org.kie.api.definition.type.Label("VehicleAge")
   private int vehicleAge;

   @org.kie.api.definition.type.Label("ECOA")
   private java.lang.String ecoa;

   @org.kie.api.definition.type.Label("BadRate")
   private java.lang.Float badRate;

   @org.kie.api.definition.type.Label("BaseRate")
   private java.math.BigDecimal baseRate;

   @org.kie.api.definition.type.Label(value = "AdjustmentsList")
   private java.util.List<engine.pricing.Adjustment> adjustmentsList;

   public Input()
   {
   }

   public java.lang.String getProduct()
   {
      return this.product;
   }

   public void setProduct(java.lang.String product)
   {
      this.product = product;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public int getZip()
   {
      return this.zip;
   }

   public void setZip(int zip)
   {
      this.zip = zip;
   }

   public int getCustomerScore()
   {
      return this.customerScore;
   }

   public void setCustomerScore(int customerScore)
   {
      this.customerScore = customerScore;
   }

   public int getVantageScore()
   {
      return this.vantageScore;
   }

   public void setVantageScore(int vantageScore)
   {
      this.vantageScore = vantageScore;
   }

   public int getTier()
   {
      return this.tier;
   }

   public void setTier(int tier)
   {
      this.tier = tier;
   }

   public java.lang.String getVehicleType()
   {
      return this.vehicleType;
   }

   public void setVehicleType(java.lang.String vehicleType)
   {
      this.vehicleType = vehicleType;
   }

   public int getVehicleModelYear()
   {
      return this.vehicleModelYear;
   }

   public void setVehicleModelYear(int vehicleModelYear)
   {
      this.vehicleModelYear = vehicleModelYear;
   }

   public java.lang.String getVechicleMake()
   {
      return this.vechicleMake;
   }

   public void setVechicleMake(java.lang.String vechicleMake)
   {
      this.vechicleMake = vechicleMake;
   }

   public java.lang.String getVehicleModel()
   {
      return this.vehicleModel;
   }

   public void setVehicleModel(java.lang.String vehicleModel)
   {
      this.vehicleModel = vehicleModel;
   }

   public int getVehicleMileage()
   {
      return this.vehicleMileage;
   }

   public void setVehicleMileage(int vehicleMileage)
   {
      this.vehicleMileage = vehicleMileage;
   }

   public java.lang.String getVehicleClass()
   {
      return this.vehicleClass;
   }

   public void setVehicleClass(java.lang.String vehicleClass)
   {
      this.vehicleClass = vehicleClass;
   }

   public int getLoanAmount()
   {
      return this.loanAmount;
   }

   public void setLoanAmount(int loanAmount)
   {
      this.loanAmount = loanAmount;
   }

   public int getNetDownPayment()
   {
      return this.netDownPayment;
   }

   public void setNetDownPayment(int netDownPayment)
   {
      this.netDownPayment = netDownPayment;
   }

   public int getLoanTerm()
   {
      return this.loanTerm;
   }

   public void setLoanTerm(int loanTerm)
   {
      this.loanTerm = loanTerm;
   }

   public int getVehicleValue()
   {
      return this.vehicleValue;
   }

   public void setVehicleValue(int vehicleValue)
   {
      this.vehicleValue = vehicleValue;
   }

   public int getVehicleAge()
   {
      return this.vehicleAge;
   }

   public void setVehicleAge(int vehicleAge)
   {
      this.vehicleAge = vehicleAge;
   }

   public java.math.BigDecimal getLtv()
   {
      return this.ltv;
   }

   public void setLtv(java.math.BigDecimal ltv)
   {
      this.ltv = ltv;
   }

   public java.math.BigDecimal getPti()
   {
      return this.pti;
   }

   public void setPti(java.math.BigDecimal pti)
   {
      this.pti = pti;
   }

   public java.math.BigDecimal getDti()
   {
      return this.dti;
   }

   public void setDti(java.math.BigDecimal dti)
   {
      this.dti = dti;
   }

   public java.lang.String getEcoa()
   {
      return this.ecoa;
   }

   public void setEcoa(java.lang.String ecoa)
   {
      this.ecoa = ecoa;
   }

   public java.lang.Float getBadRate()
   {
      return this.badRate;
   }

   public void setBadRate(java.lang.Float badRate)
   {
      this.badRate = badRate;
   }

   public java.math.BigDecimal getBaseRate()
   {
      return this.baseRate;
   }

   public void setBaseRate(java.math.BigDecimal baseRate)
   {
      this.baseRate = baseRate;
   }

   public java.util.List<engine.pricing.Adjustment> getAdjustmentsList()
   {
      return this.adjustmentsList;
   }

   public void setAdjustmentsList(
         java.util.List<engine.pricing.Adjustment> adjustmentsList)
   {
      this.adjustmentsList = adjustmentsList;
   }

   public Input(java.lang.String product, java.lang.String state, int zip,
         int customerScore, int vantageScore, int tier,
         java.lang.String vehicleType, int vehicleModelYear,
         java.lang.String vechicleMake, java.lang.String vehicleModel,
         int vehicleMileage, java.lang.String vehicleClass,
         java.math.BigDecimal ltv, java.math.BigDecimal pti,
         java.math.BigDecimal dti, int loanAmount, int netDownPayment,
         int loanTerm, int vehicleValue, int vehicleAge, java.lang.String ecoa,
         java.lang.Float badRate, java.math.BigDecimal baseRate,
         java.util.List<engine.pricing.Adjustment> adjustmentsList)
   {
      this.product = product;
      this.state = state;
      this.zip = zip;
      this.customerScore = customerScore;
      this.vantageScore = vantageScore;
      this.tier = tier;
      this.vehicleType = vehicleType;
      this.vehicleModelYear = vehicleModelYear;
      this.vechicleMake = vechicleMake;
      this.vehicleModel = vehicleModel;
      this.vehicleMileage = vehicleMileage;
      this.vehicleClass = vehicleClass;
      this.ltv = ltv;
      this.pti = pti;
      this.dti = dti;
      this.loanAmount = loanAmount;
      this.netDownPayment = netDownPayment;
      this.loanTerm = loanTerm;
      this.vehicleValue = vehicleValue;
      this.vehicleAge = vehicleAge;
      this.ecoa = ecoa;
      this.badRate = badRate;
      this.baseRate = baseRate;
      this.adjustmentsList = adjustmentsList;
   }

}