package engine.pricing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Tier implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Bad Rate")
   private float badRate;
   @org.kie.api.definition.type.Label(value = "Tier")
   private int tier;

   public Tier()
   {
   }

   public Tier(int tier)
   {
	this.tier = tier;
   }

   public float getBadRate()
   {
      return this.badRate;
   }

   public void setBadRate(float badRate)
   {
      this.badRate = badRate;
   }

   public int getTier()
   {
      return this.tier;
   }

   public void setTier(int tier)
   {
      this.tier = tier;
   }

   public Tier(float badRate, int tier)
   {
      this.badRate = badRate;
      this.tier = tier;
   }

}