package check;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Input implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "State Code")
   private java.lang.String stateCode;

   @org.kie.api.definition.type.Label(value = "VIN Check Required")
   private boolean vinCheckRequired;

   public Input()
   {
   }

   public java.lang.String getStateCode()
   {
      return this.stateCode;
   }

   public void setStateCode(java.lang.String stateCode)
   {
      this.stateCode = stateCode;
   }

   public boolean isVinCheckRequired()
   {
      return this.vinCheckRequired;
   }

   public void setVinCheckRequired(boolean vinCheckRequired)
   {
      this.vinCheckRequired = vinCheckRequired;
   }

   public Input(java.lang.String stateCode, boolean vinCheckRequired)
   {
      this.stateCode = stateCode;
      this.vinCheckRequired = vinCheckRequired;
   }

}