package vehicle.eligibility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InspectionRequired implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Make")
   private java.lang.String make;
   @org.kie.api.definition.type.Label(value = "Age")
   private java.lang.Integer age;
   @org.kie.api.definition.type.Label(value = "Mileage")
   private java.lang.Integer mileage;
   @org.kie.api.definition.type.Label(value = "Required")
   private boolean required;

   public InspectionRequired()
   {
   }

   public java.lang.String getMake()
   {
      return this.make;
   }

   public void setMake(java.lang.String make)
   {
      this.make = make;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.Integer getMileage()
   {
      return this.mileage;
   }

   public void setMileage(java.lang.Integer mileage)
   {
      this.mileage = mileage;
   }

   public boolean isRequired()
   {
      return this.required;
   }

   public void setRequired(boolean required)
   {
      this.required = required;
   }

   public InspectionRequired(java.lang.String make, java.lang.Integer age,
         java.lang.Integer mileage, boolean required)
   {
      this.make = make;
      this.age = age;
      this.mileage = mileage;
      this.required = required;
   }

}