package vehicle.eligibility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IsLTVPTIEligible implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Product")
   private java.lang.String product;
   @org.kie.api.definition.type.Label(value = "TIER")
   private int tier;
   @org.kie.api.definition.type.Label(value = "LTV")
   private java.math.BigDecimal ltv;
   @org.kie.api.definition.type.Label(value = "PTI")
   private java.math.BigDecimal pti;
   @org.kie.api.definition.type.Label(value = "Is LTV PTI Eligible")
   private java.lang.String isLTVPTIEligible;

   public IsLTVPTIEligible()
   {
   }

   public java.lang.String getProduct()
   {
      return this.product;
   }

   public void setProduct(java.lang.String product)
   {
      this.product = product;
   }

   public int getTier()
   {
      return this.tier;
   }

   public void setTier(int tier)
   {
      this.tier = tier;
   }

   public java.math.BigDecimal getLtv()
   {
      return this.ltv;
   }

   public void setLtv(java.math.BigDecimal ltv)
   {
      this.ltv = ltv;
   }

   public java.math.BigDecimal getPti()
   {
      return this.pti;
   }

   public void setPti(java.math.BigDecimal pti)
   {
      this.pti = pti;
   }

   public java.lang.String getIsLTVPTIEligible()
   {
      return this.isLTVPTIEligible;
   }

   public void setIsLTVPTIEligible(java.lang.String isLTVPTIEligible)
   {
      this.isLTVPTIEligible = isLTVPTIEligible;
   }

   public IsLTVPTIEligible(java.lang.String product, int tier,
         java.math.BigDecimal ltv, java.math.BigDecimal pti,
         java.lang.String isLTVPTIEligible)
   {
      this.product = product;
      this.tier = tier;
      this.ltv = ltv;
      this.pti = pti;
      this.isLTVPTIEligible = isLTVPTIEligible;
   }

}