package vehicle.eligibility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IsModelEligible implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Vehicle Model")
   private java.lang.String vehicleModel;
   @org.kie.api.definition.type.Label("Is Vehicle Model Eligible")
   private boolean isModelEligible;

   @org.kie.api.definition.type.Label(value = "Vehicle Make")
   private java.lang.String vehicleMake;

   public IsModelEligible()
   {
   }

   public java.lang.String getVehicleModel()
   {
      return this.vehicleModel;
   }

   public void setVehicleModel(java.lang.String vehicleModel)
   {
      this.vehicleModel = vehicleModel;
   }

   public boolean isIsModelEligible()
   {
      return this.isModelEligible;
   }

   public void setIsModelEligible(boolean isModelEligible)
   {
      this.isModelEligible = isModelEligible;
   }

   public java.lang.String getVehicleMake()
   {
      return this.vehicleMake;
   }

   public void setVehicleMake(java.lang.String vehicleMake)
   {
      this.vehicleMake = vehicleMake;
   }

   public IsModelEligible(java.lang.String vehicleModel, boolean isModelEligible,
         java.lang.String vehicleMake)
   {
      this.vehicleModel = vehicleModel;
      this.isModelEligible = isModelEligible;
      this.vehicleMake = vehicleMake;
   }

}