package vehicle.eligibility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IsVehicleYearEligible implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Vehicle Year")
   private int vehicleYear;
   @org.kie.api.definition.type.Label(value = "Is Vehicle Year Eligible")
   private boolean isVehicleYearEligible;

   public IsVehicleYearEligible()
   {
   }

   public int getVehicleYear()
   {
      return this.vehicleYear;
   }

   public void setVehicleYear(int vehicleYear)
   {
      this.vehicleYear = vehicleYear;
   }

   public boolean isIsVehicleYearEligible()
   {
      return this.isVehicleYearEligible;
   }

   public void setIsVehicleYearEligible(boolean isVehicleYearEligible)
   {
      this.isVehicleYearEligible = isVehicleYearEligible;
   }

   public IsVehicleYearEligible(int vehicleYear, boolean isVehicleYearEligible)
   {
      this.vehicleYear = vehicleYear;
      this.isVehicleYearEligible = isVehicleYearEligible;
   }

}