package vehicle.eligibility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Output implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Tolerance Name")
   private java.lang.String toleranceName;
   @org.kie.api.definition.type.Label("Max Term")
   private int maxTerm;
   @org.kie.api.definition.type.Label("Min Amount")
   private long minAmount;
   @org.kie.api.definition.type.Label("Max Amount")
   private int maxAmount;
   @org.kie.api.definition.type.Label("Max Payment")
   private int maxPayment;
   @org.kie.api.definition.type.Label("Max LTV")
   private int maxLTV;

   public Output()
   {
   }

   public int getMaxTerm()
   {
      return this.maxTerm;
   }

   public void setMaxTerm(int maxTerm)
   {
      this.maxTerm = maxTerm;
   }

   public long getMinAmount()
   {
      return this.minAmount;
   }

   public void setMinAmount(long minAmount)
   {
      this.minAmount = minAmount;
   }

   public int getMaxAmount()
   {
      return this.maxAmount;
   }

   public void setMaxAmount(int maxAmount)
   {
      this.maxAmount = maxAmount;
   }

   public int getMaxPayment()
   {
      return this.maxPayment;
   }

   public void setMaxPayment(int maxPayment)
   {
      this.maxPayment = maxPayment;
   }

   public int getMaxLTV()
   {
      return this.maxLTV;
   }

   public void setMaxLTV(int maxLTV)
   {
      this.maxLTV = maxLTV;
   }

   public java.lang.String getToleranceName()
   {
      return this.toleranceName;
   }

   public void setToleranceName(java.lang.String toleranceName)
   {
      this.toleranceName = toleranceName;
   }

   public Output(java.lang.String toleranceName, int maxTerm, long minAmount,
         int maxAmount, int maxPayment, int maxLTV)
   {
      this.toleranceName = toleranceName;
      this.maxTerm = maxTerm;
      this.minAmount = minAmount;
      this.maxAmount = maxAmount;
      this.maxPayment = maxPayment;
      this.maxLTV = maxLTV;
   }

}